1: https://raw.githubusercontent.com/qq5460168/666/master/dns.txt
3: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt
4: https://raw.githubusercontent.com/3316134332/qy-Ads-Rule/refs/heads/main/black.txt
5: https://raw.githubusercontent.com/2Gardon/SM-Ad-FuckU-hosts/refs/heads/master/SMAdHosts
7: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/AdGuard/Advertising/Advertising.txt
9: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/AdGuard/Privacy/Privacy.txt
10: https://raw.githubusercontent.com/Sereinfy/Adrules/main/rules/adblockdns.txt
