https://raw.githubusercontent.com/qq5460168/666/master/dns.txt
https://raw.githubusercontent.com/2771936993/HG/main/hg1.txt
https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt
https://raw.githubusercontent.com/3316134332/qy-Ads-Rule/refs/heads/main/black.txt
https://raw.githubusercontent.com/2Gardon/SM-Ad-FuckU-hosts/refs/heads/master/SMAdHosts
https://filters.adtidy.org/android/filters/15_optimized.txt
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/AdGuard/Advertising/Advertising.txt
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/AdGuard/Advertising
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/AdGuard/Privacy/Privacy.txt
https://raw.githubusercontent.com/Sereinfy/Adrules/main/rules/adblockdns.txt
